'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

export default function EditPostPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter();
  const [form, setForm] = useState({ title: '', slug: '', excerpt: '', content: '', status: 'draft', category_id: '', series_id: '', series_order: '', tags: '', seo_title: '', seo_description: '', reading_time_minutes: '5' });
  const [categories, setCategories] = useState<{ id: string; name: string }[]>([]); const [series, setSeries] = useState<{ id: string; name: string }[]>([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));

  useEffect(() => { const load = async () => { const supabase = createClient(); const [{ data: post }, { data: cats }, { data: ser }] = await Promise.all([supabase.from('posts').select('*').eq('id', id).single(), supabase.from('categories').select('id,name').order('sort_order'), supabase.from('series').select('id,name').order('name')]); if (!post) { router.push('/admin'); return; } const { data: tagRows } = await supabase.from('post_tags').select('tags(name)').eq('post_id', id); setForm({ title: post.title, slug: post.slug, excerpt: post.excerpt, content: post.content, status: post.status, category_id: post.category_id ?? '', series_id: post.series_id ?? '', series_order: post.series_order?.toString() ?? '', tags: (tagRows ?? []).map((row: any) => row.tags?.name).filter(Boolean).join(', '), seo_title: post.seo_title ?? '', seo_description: post.seo_description ?? '', reading_time_minutes: String(post.reading_time_minutes ?? 5) }); setCategories(cats ?? []); setSeries(ser ?? []); setLoading(false); }; load(); }, [id, router]);

  async function save(event: FormEvent, status: 'draft' | 'published') { event.preventDefault(); setSaving(true); setMessage(''); const supabase = createClient(); const { error } = await supabase.from('posts').update({ title: form.title, slug: form.slug, excerpt: form.excerpt, content: form.content, category_id: form.category_id || null, series_id: form.series_id || null, series_order: form.series_order ? Number(form.series_order) : null, status, published_at: status === 'published' ? new Date().toISOString() : null, reading_time_minutes: Number(form.reading_time_minutes) || 1, seo_title: form.seo_title || form.title, seo_description: form.seo_description || form.excerpt }).eq('id', id); if (error) { setMessage(error.message); setSaving(false); return; } await supabase.from('post_tags').delete().eq('post_id', id); for (const name of form.tags.split(',').map((tag) => tag.trim()).filter(Boolean)) { const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); const { data: tag } = await supabase.from('tags').upsert({ name, slug }, { onConflict: 'slug' }).select('id').single(); if (tag) await supabase.from('post_tags').insert({ post_id: id, tag_id: tag.id }); } router.push('/admin'); router.refresh(); }

  if (loading) return <section className="section container"><p>Loading article…</p></section>;
  return <section className="section container admin-editor"><div className="section-title"><span>Publishing</span><h1>Edit article</h1></div><form className="editor-form" onSubmit={(event) => save(event, form.status === 'published' ? 'published' : 'draft')}><label>Title<input value={form.title} onChange={(e) => update('title', e.target.value)} required /></label><label>Slug<input value={form.slug} onChange={(e) => update('slug', e.target.value)} required /></label><div className="form-grid"><label>Category<select value={form.category_id} onChange={(e) => update('category_id', e.target.value)}><option value="">No category</option>{categories.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Series<select value={form.series_id} onChange={(e) => update('series_id', e.target.value)}><option value="">No series</option>{series.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Part<input type="number" min="1" value={form.series_order} onChange={(e) => update('series_order', e.target.value)} /></label><label>Minutes<input type="number" min="1" value={form.reading_time_minutes} onChange={(e) => update('reading_time_minutes', e.target.value)} /></label></div><label>Tags <small>comma separated</small><input value={form.tags} onChange={(e) => update('tags', e.target.value)} /></label><label>Excerpt<textarea rows={3} value={form.excerpt} onChange={(e) => update('excerpt', e.target.value)} required /></label><label>Article content<textarea className="content-editor" rows={24} value={form.content} onChange={(e) => update('content', e.target.value)} required /></label><div className="form-grid"><label>SEO title<input value={form.seo_title} onChange={(e) => update('seo_title', e.target.value)} /></label><label>SEO description<textarea rows={2} value={form.seo_description} onChange={(e) => update('seo_description', e.target.value)} /></label></div>{message && <p className="form-error" role="alert">{message}</p>}<div className="editor-actions"><button className="button secondary" type="button" disabled={saving} onClick={(e) => save(e as unknown as FormEvent, 'draft')}>Save draft</button><button className="button primary" type="button" disabled={saving} onClick={(e) => save(e as unknown as FormEvent, 'published')}>Publish changes →</button></div></form></section>;
}
